import type { Metadata } from "next";
import { Jost } from "next/font/google";
import "./globals.scss";
import Layout from "@/featured/layout/layout";
import { ToastContainer } from "react-toastify";
import 'react-toastify/dist/ReactToastify.css';


const jost = Jost({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-jost",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${jost.variable} antialiased bg-[#F0EEEF]`}>
        <Layout>
          {children}
        </Layout>

        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
        />

        <script src="//code.tidio.co/xywkea6yqjsmb7fxs63spcmdgr1fudry.js" async></script>
      </body>
    </html>
  );
}
